#ifndef ENGINE_WRAPPER_EXPORT
#define ENGINE_WRAPPER_EXPORT
#include <QObject>

#ifdef ENGINE_WRAPPER_DLL
#define ENGINE_WRAPPER_API Q_DECL_EXPORT
#else
#define ENGINE_WRAPPER_API Q_DECL_IMPORT
#endif
#endif // ENGINE_WRAPPER_EXPORT